### PR TITLE
Bayes kits

### PR DESCRIPTION
**Pull request by lukasschwab**
This is the first step in a migration to just using the Bayes Impact GitHub repo as the go-to place for prompts resources.

After a verification process and adding additional resource links currently listed on the prompts pages to the repos, we will link straight to the repos from bayeshack.org (instead of to website prompts pages). This will be good.

This is just so we can get the logistics emails out.

### CODE REVIEW

**Comment by lukasschwab** [comment]
Oops

**Comment by canzhiye** [comment]
lol 👍

**Comment by Zhipan1** [comment]
🔥

**Comment by twofactor** [comment]
lol

**Pull request closed without merging**
