### PR TITLE
Remove index.php and simplify index.html

### PR DESCRIPTION
**Pull request by kevinji**
The `index.php` was literally not doing anything useful.

### CODE REVIEW

**Comment by Zhipan1** [comment]
Yikessss! Sorry but we can't remove php. Heroku doesn't do static hosting so it's a tiny hack to host our site there.

**Comment by kevinji** [comment]
I'll rename the file `index.php` then?

**Comment by kevinji** [comment]
Also if everything's static you could probably host everything for free on GitHub Pages.

**Comment by Zhipan1** [comment]
lol our site was heroku last year. Didn't want to wait a day for the DNS to propagate if we switched to GitHub

**Comment by Zhipan1** [comment]
Your edits for html is awesome tho! Thanks :)

**Comment by kevinji** [comment]
Fixed the commits and got rid of some HTML errors in the process.

**Comment by canzhiye** [comment]
Can we close this?

**Comment by Zhipan1** [comment]
Wait can you decouple index.php back into home.html and index.php. Just want to keep the php hack seperate from the html.

**Comment by kevinji** [comment]
Aight fine.

**Comment by Zhipan1** [comment]
<3

**Pull request merged**
